#' CorSignificantPlot :
#' @description Prints or saves the genes found to be most significant by \link{CorSignificantPlot} or \link{CorAnalysisPar}
#'
#' @param results A dataframe generated by \code{CorAnalysis}
#' @param dataset A transcriptomics dataset which was used with \code{CorAnalysis} to generate the results dataframe. First columns should be gene names. All other columns should be expression levels.
#' @param number The number of most significant genes printed or saved
#' @param period The period of rhythmicity which is being tested for. Defaults to 24 (Circadian).
#' @param save Logical. If TRUE, saves plots to working directory. Defaults to FALSE.
#' @param print Logical. If TRUE renders significant genes in the plot viewer. Defaults to TRUE
#' @return Prints or saves ggplot2 object(s).
#' @examples
#' cor_results <- coranalysis('comp100002_c0_seq2',Laurasmappings)
#' corsignificantplot(cor_results, Laurasmappings, number = 15,save=TRUE, negative=FALSE)
#'
#' @export
CorSignificantPlot <- function(results, dataset, number = 10, print = TRUE, save = FALSE, negative = FALSE) {
    results <- results[order(results$correlation, decreasing = TRUE), ]  # Order by most positive correlation
    gene1 <- as.character(results[1, 1])
    if (save == TRUE) {
        directory <- paste("cor_", gene1)
        if (dir.exists(directory) == FALSE) {
            dir.create(directory)
        }
    }
    if (negative == FALSE) {
        for (i in 2:(number + 1)) {
            myplot <- CircadianTools::CompPlot(as.character(gene1), as.character(results[i, 1]), dataset)
            myplot <- myplot + ggplot2::ggtitle(paste(" Correlation = ", as.character(results[i, 2])))

            if (print == TRUE) {
                print(myplot)
            }

            if (save == TRUE) {
                ggplot2::ggsave(paste("rank=", i - 1, "Cor_", as.character(results[i, 1]), ".png"), myplot, path = directory,
                  width = 10, height = 4.5, units = "in")
            }
        }
    }
    if (negative == TRUE) {
        results <- results[order(results$correlation, decreasing = FALSE), ]
        for (i in 1:number) {
            myplot <- CircadianTools::CompPlot(as.character(gene1), as.character(results[i, 1]), dataset)
            myplot <- myplot + ggplot2::ggtitle(paste("Gene = ", as.character(results[i, 1]), " Cor = ", as.character(results[i,
                2])))

            if (print == TRUE) {
                print(myplot)
            }

            if (save == TRUE) {
                ggplot2::ggsave(paste("rank=", i, "Cor_", as.character(results[i, 1]), ".png"), myplot, path = directory,
                  width = 10, height = 4.5, units = "in")
            }
        }
    }
}
