#' CosinorSignificantPlot :
#' @description Prints or saves the genes found to be most significant by \link{CosinorAnalysis}
#'
#' @param results A dataframe generated by \code{CosinorAnalysis}
#' @param dataset A transcriptomics dataset which was used with \code{CosinorAnalysis} to generate the results dataframe. First columns should be gene names. All other columns should be expression levels.
#' @param number The number of most significant genes printed or saved
#' @param period The period of rhythmicity which is being tested for. Defaults to 24 (circadian).
#' @param save Logical. If TRUE, saves plots to working directory. Defaults to FALSE.
#' @param print Logical. If TRUE renders significant genes in the plot viewer. Defaults to TRUE
#' @return Prints or saves ggplot2 object(s).
#' @examples
#' cosinor_results <- CosinorAnalysis(Laurasmappings)
#' CosinorSignificantPlot(cosinor_results, Laurasmappings, number = 15, period=24 ,save=TRUE)
#'
#' @export
CosinorSignificantPlot <- function(results, dataset, number = 10, period = 24, print = TRUE, save = FALSE) {
    results <- results[order(results$pVal), ]  # Order by most significant p-value

    for (i in 1:number) {
        myplot <- CircadianTools::CosinorPlot(as.character(results[i, 1]), dataset, period = period)
        myplot <- myplot + ggplot2::ggtitle(paste("Gene = ", as.character(results[i, 1]), " P-Value = ", as.character(results[i,
            2])))

        if (print == TRUE) {
            print(myplot)
        }

        if (save == TRUE) {
            ggplot2::ggsave(paste("rank=", i, "Cosinor_", as.character(results[i, 1]), ".png"), myplot, width = 10,
                height = 4.5, units = "in")
        }
    }
}
