#' rainsignificantplot :
#' Prints or saves the genes found to be most significant by \code{rainanalysis}
#'
#' @param results A dataframe generated by \code{rainanalysis}
#' @param dataset A transcriptomics dataset which was used with \code{rainanalysis} to generate the results dataframe. First columns should be gene names. All other columns should be expression levels.
#' @param number The number of most significant genes printed or saved
#' @param save Logical. If TRUE, saves plots to working directory. Defaults to FALSE.
#' @param print Logical. If TRUE renders significant genes in the plot viewer. Defaults to TRUE
#' @return Prints or saves ggplot2 object(s).
#' @examples
#' results <- rainanalysis(Laurasmappings)
#' rainsignificantplot(results,Laurasmappings, save=TRUE, number=15)
rainsignificantplot <- function(results, dataset, number = 10, print = TRUE, save = FALSE) {
    results <- results[order(results$pVal), ]  # Order by most significant p-value

    for (i in 1:number) {
        myplot <- basicplot(as.character(results[i, 1]), dataset)
        myplot <- myplot + ggplot2::ggtitle(paste("Gene = ", as.character(results[i, 1]), " P-Value = ", as.character(results[i, 2])))

        if (print == TRUE) {
            print(myplot)
        }

        if (save == TRUE) {
            ggplot2::ggsave(paste("rank=", i, "RAIN_", as.character(results[i, 1]), ".png"), myplot, width = 10, height = 4.5, units = "in")
        }

    }

}
